# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65c0a0656c56a1152fe9db3e03218fe1658989a77a0e8e210a603a766677e804c457b720b18f6974d9730b7b34c7b217073815f2ef5765fd1f4f90450390b156

test:
  secret_key_base: 5324abd09d38525c873df60bb07f9a0292919f134dfda9b2b633735c418b7f3c130238659c89bc0f49bdb2c910f0f5bb36928b0e58fb9eb56d0c2ce318d0ffcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
